name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        configs: [Release, Debug]
    steps:
    - name: boost
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-program-options-dev
        else
                echo "$RUNNER_OS not supported" exit 1
        fi
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        config: ${{ matrix.configs }}
        submodule_update: ON
        run_tests: ON
        unit_test_build: -DFIND_TESTS=ON
        cmake_args: -DFIND_MODULES=ON;-DENABLE_TIDY=ON
        create_package: ON
    - uses: actions/upload-artifact@v2
      with:
        path: build/*.tar.gz
        name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
    - name: Test run
      run: |
        cd build
        time ./HashCalculator --input=./HashCalculator --output=./out.txt --size=40
        time md5sum ./HashCalculator
